"""Epistemic Interfaces — protocol definitions for all epistemic components.

These protocols define the contracts that epistemic components must satisfy.
They enable clean dependency injection, testing, and future extension
without tight coupling between subsystems.

The epistemic runtime is **domain-neutral**.  It knows about observations,
evidence, uncertainty, hypotheses, predictions, experiments, and belief
revision — never about medicine, robotics, chemistry, or finance.
Domain knowledge arrives through plugins and ontologies.

Protocols::

    IBeliefReviser            — update beliefs from evidence
    IIdeaGenerator            — generate raw ideas from knowledge gaps
    IHypothesisBuilder        — validate/filter/deduplicate ideas → HypothesisNode
    IPredictionTracker        — track competing predictions against observations
    IExperimentDesigner       — design info-gain-optimized experiments
    IContradictionSeeker      — actively search for contradictions & anomalies
    IEvidenceEvaluator        — score evidence quality, weight, bias, trust
    ICuriosityEngine          — self-directed investigation prioritization
    IExplanationEngine        — "why do you believe this?" via graph traversal
    ISourceReputationTracker  — track source reliability over time

Usage::

    class MyBeliefReviser(IBeliefReviser):
        async def revise_belief(self, belief_id, evidence_id) -> BeliefRevision:
            ...
"""

from __future__ import annotations

import time
from dataclasses import dataclass, field
from typing import Any, Protocol, runtime_checkable

# ═══════════════════════════════════════════════════════════════════════════
# Shared Data Types
# ═══════════════════════════════════════════════════════════════════════════


@dataclass
class BeliefRevision:
    """Record of a belief confidence change."""

    belief_id: str = ""
    old_confidence: float = 0.0
    new_confidence: float = 0.0
    reason: str = ""
    evidence_id: str = ""
    timestamp: float = field(default_factory=time.time)


@dataclass
class RawIdea:
    """An unvalidated idea from the LLM — quantity over quality.

    RawIdeas are generated by the IdeaGenerator and consumed by the
    HypothesisBuilder.  They are deliberately unconstrained and are
    never promoted directly to HCIR nodes.
    """

    claim: str = ""  # The proposed explanation or mechanism
    plausibility: float = 0.5  # Self-assessed plausibility (LLM estimate)
    origin_trigger: str = ""  # DiscoveryTrigger value that spawned this
    origin_id: str = ""  # ID of the node that triggered generation
    reasoning: str = ""  # LLM's reasoning for this idea
    domain: str = ""  # Knowledge domain (if identifiable)


@dataclass
class HypothesisCandidate:
    """A validated, deduplicated hypothesis candidate ready for HCIR promotion.

    Produced by the HypothesisBuilder after filtering RawIdeas.
    """

    claim: str = ""
    novelty: float = 0.5
    plausibility: float = 0.5
    predicted_impact: float = 0.5
    testability: float = 0.5
    supporting_evidence: list[str] = field(default_factory=list)
    missing_evidence: list[str] = field(default_factory=list)
    origin: str = ""  # "contradiction", "analogy", "anomaly", "gap", "curiosity"
    reasoning: str = ""  # Why this hypothesis survived the filter


@dataclass
class ExperimentDesign:
    """A proposed experiment design before it becomes an HCIR node."""

    hypothesis_ids: list[str] = field(default_factory=list)
    design: str = ""
    variables: dict[str, Any] = field(default_factory=dict)
    controls: list[str] = field(default_factory=list)
    expected_outcomes: dict[str, str] = field(default_factory=dict)
    discriminating_power: float = 0.5
    estimated_cost: float = 0.0
    expected_information_gain: float = 0.0  # Bayesian info gain estimate
    reality_level: str = "simulation"
    reasoning: str = ""  # Why this experiment was designed


@dataclass
class PredictionOutcome:
    """Result of checking a prediction against observation."""

    prediction_id: str = ""
    hypothesis_id: str = ""
    predicted: str = ""
    observed: str = ""
    correct: bool | None = None
    confidence_delta: float = 0.0
    timestamp: float = field(default_factory=time.time)


@dataclass
class ContradictionReport:
    """A discovered contradiction between claims or evidence."""

    claim_a_id: str = ""
    claim_b_id: str = ""
    contradiction_type: str = ""
    possible_explanations: list[str] = field(default_factory=list)
    investigation_priority: float = 0.5
    context: str = ""


@dataclass
class EvidenceAssessment:
    """Result of evaluating a piece of evidence.

    Produced by the EvidenceEvaluator.  Each dimension feeds
    directly into the corresponding BeliefConfidence dimension
    during belief revision.
    """

    evidence_id: str = ""
    quality_score: float = 0.5  # Methodology + sample size + reproducibility
    weight: float = 0.5  # Final weight for belief revision [0.0, 1.0]
    bias_flags: list[str] = field(default_factory=list)  # e.g. "confirmation", "selection"
    trust_adjustment: float = 1.0  # Source reputation multiplier
    reality_level_weight: float = 0.5  # Weight from experiment reality level
    reproducibility_status: str = ""  # "not_attempted", "reproduced", "failed_replication"
    reasoning: str = ""  # LLM explanation of assessment


@dataclass
class CuriositySignal:
    """An investigation candidate produced by any epistemic engine.

    CuriositySignals are consumed and prioritized by the CuriosityEngine.
    They can originate from contradictions, anomalies, knowledge gaps,
    unexpected outcomes, or spontaneous scanning.
    """

    unknown_id: str = ""  # Target UnknownNode (or "" if not yet created)
    trigger: str = ""  # DiscoveryTrigger value
    source_engine: str = ""  # Which engine produced this signal
    source_id: str = ""  # Source node ID (observation, contradiction, etc.)
    estimated_info_gain: float = 0.5  # Expected information gain if investigated
    estimated_impact: float = 0.5  # Potential impact of findings
    estimated_cost: float = 0.0  # Expected investigation cost
    description: str = ""  # Human-readable description of the signal


@dataclass
class EpistemicTask:
    """A typed task for the epistemic loop orchestrator queue.

    Tasks are dispatched by the EpistemicLoop and executed by workers.
    They are Message-based, enabling future swarm execution.
    """

    task_type: str = ""  # "generate_ideas", "build_hypothesis", etc.
    program_id: str = ""  # Research program context
    target_ids: list[str] = field(default_factory=list)  # Node IDs to operate on
    priority: float = 0.5
    strategy: str = ""  # ResearchStrategyType value
    budget: float = 0.0  # Resource budget for this task
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass
class ExplanationChain:
    """A graph-traversal result explaining why a belief is held.

    Not generated text — a structured chain of HCIR nodes
    from belief back to observations.  Each step includes the
    edge type and confidence contribution.
    """

    belief_id: str = ""
    belief_claim: str = ""
    derived_confidence: float = 0.0
    steps: list[ExplanationStep] = field(default_factory=list)
    counter_evidence: list[ExplanationStep] = field(default_factory=list)


@dataclass
class ExplanationStep:
    """A single step in an explanation chain."""

    node_id: str = ""
    node_type: str = ""  # HCIRNodeType value
    edge_type: str = ""  # HCIREdgeType value (from parent)
    label: str = ""  # Human-readable label
    confidence_contribution: float = 0.0
    source_uri: str = ""  # Provenance URI if available


@dataclass
class InvestigationBudget:
    """Resource constraints for epistemic investigations.

    Every investigation has a cost.  The CuriosityEngine must
    optimize Expected Value / Expected Cost, not just Information Gain.
    """

    max_cpu_seconds: float = 60.0  # CPU time budget
    max_llm_calls: int = 10  # LLM API call budget
    max_wall_time_seconds: float = 300.0  # Wall-clock time budget
    max_experiments: int = 5  # Maximum experiments to run
    attention_cost: float = 0.1  # Human attention required [0=none, 1=full]
    risk_tolerance: float = 0.5  # Acceptable risk level [0=none, 1=any]


# ═══════════════════════════════════════════════════════════════════════════
# Protocol Definitions
# ═══════════════════════════════════════════════════════════════════════════


@runtime_checkable
class IBeliefReviser(Protocol):
    """Updates beliefs based on new evidence.

    Wraps the existing ``BeliefStore`` to add discovery-aware lifecycle:
    belief creation → evidence addition → prediction generation →
    prediction testing → confidence update → belief revision.

    Belief revision updates ``BeliefConfidence`` dimensions individually,
    not a single opaque confidence number.
    """

    async def revise_belief(
        self,
        belief_id: str,
        evidence_id: str,
        direction: str,  # "supporting" | "contradicting"
    ) -> BeliefRevision:
        """Update a belief's confidence based on new evidence."""
        ...

    async def revise_from_prediction(
        self,
        belief_id: str,
        prediction_outcome: PredictionOutcome,
    ) -> BeliefRevision:
        """Update a belief based on a prediction outcome (Bayesian update)."""
        ...

    async def get_falsification_candidates(
        self,
        domain: str = "",
        min_confidence: float = 0.3,
        max_confidence: float = 0.9,
    ) -> list[str]:
        """Return belief IDs that are good candidates for falsification testing."""
        ...


@runtime_checkable
class IIdeaGenerator(Protocol):
    """Generates raw ideas from knowledge gaps, contradictions, and anomalies.

    Deliberately unconstrained — quantity over quality.
    Returns ``RawIdea`` objects (not HypothesisCandidate).
    Filtering and validation is the HypothesisBuilder's responsibility.
    """

    async def generate_from_unknown(
        self,
        unknown_id: str,
        context: dict[str, Any] | None = None,
    ) -> list[RawIdea]:
        """Generate raw ideas to explain a knowledge gap."""
        ...

    async def generate_from_contradiction(
        self,
        contradiction_id: str,
    ) -> list[RawIdea]:
        """Generate raw ideas to resolve a contradiction."""
        ...

    async def generate_from_analogy(
        self,
        source_domain: str,
        target_domain: str,
        structural_pattern: str,
    ) -> list[RawIdea]:
        """Generate raw ideas by cross-domain analogical reasoning."""
        ...

    async def generate_from_anomaly(
        self,
        observation_id: str,
    ) -> list[RawIdea]:
        """Generate raw ideas to explain an anomalous observation."""
        ...


@runtime_checkable
class IHypothesisBuilder(Protocol):
    """Filters, validates, deduplicates ideas into HypothesisNodes.

    The funnel: 30 raw ideas → 4 plausible → 2 novel → HypothesisNode.
    This separation ensures LLM creativity isn't constrained by
    validation logic.
    """

    async def validate(
        self,
        ideas: list[RawIdea],
    ) -> list[HypothesisCandidate]:
        """Filter raw ideas for plausibility, testability, and coherence."""
        ...

    async def deduplicate(
        self,
        candidates: list[HypothesisCandidate],
        existing_hypothesis_ids: list[str] | None = None,
    ) -> list[HypothesisCandidate]:
        """Remove candidates that are semantically equivalent to existing hypotheses."""
        ...

    async def promote_to_node(
        self,
        candidate: HypothesisCandidate,
        program_id: str = "",
    ) -> str:
        """Create an HCIR HypothesisNode from a validated candidate. Returns node ID."""
        ...


@runtime_checkable
class IPredictionTracker(Protocol):
    """Tracks competing predictions against observations (Popperian science).

    Supports rival hypotheses with conflicting predictions:
        Hypothesis A → "X will increase"
        Hypothesis B → "X will decrease"
        → Conflict detected → discriminative experiment opportunity
    """

    async def register_prediction(
        self,
        hypothesis_id: str,
        prediction_claim: str,
        predicted_outcome: str,
        time_horizon_ms: int = 0,
    ) -> str:
        """Register a new prediction. Returns prediction node ID."""
        ...

    async def register_competing_predictions(
        self,
        predictions: list[tuple[str, str, str]],
    ) -> list[str]:
        """Register multiple predictions from rival hypotheses.

        Args:
            predictions: List of (hypothesis_id, claim, predicted_outcome).

        Returns:
            List of prediction node IDs.
        """
        ...

    async def check_prediction(
        self,
        prediction_id: str,
        observed_outcome: str,
    ) -> PredictionOutcome:
        """Check a prediction against an observed outcome."""
        ...

    async def find_competing_predictions(self) -> list[tuple[str, str]]:
        """Find pairs of predictions from rival hypotheses that conflict."""
        ...

    async def get_pending_predictions(
        self,
        hypothesis_id: str = "",
    ) -> list[str]:
        """Return IDs of predictions that haven't been verified yet."""
        ...

    async def check_expired_predictions(self) -> list[PredictionOutcome]:
        """Find and evaluate predictions past their time horizon."""
        ...


@runtime_checkable
class IExperimentDesigner(Protocol):
    """Designs experiments that maximize information gain per unit cost.

    Don't ask: "Can this experiment confirm my hypothesis?"
    Ask:       "Which experiment most reduces uncertainty?"

    Integrates discovery economics: sometimes the optimal action
    is to not investigate.
    """

    async def design_discriminative_experiment(
        self,
        hypothesis_ids: list[str],
        budget: InvestigationBudget | None = None,
        max_reality_level: str = "simulation",
    ) -> ExperimentDesign:
        """Design an experiment to distinguish between hypotheses."""
        ...

    async def rank_by_information_gain(
        self,
        designs: list[ExperimentDesign],
    ) -> list[ExperimentDesign]:
        """Rank experiments by (information gain × impact) / cost."""
        ...

    async def estimate_information_gain(
        self,
        design: ExperimentDesign,
    ) -> float:
        """Estimate the expected entropy reduction from an experiment."""
        ...


@runtime_checkable
class IContradictionSeeker(Protocol):
    """Actively searches for contradictions and anomalies.

    Contradictions are not errors — they are opportunities.
    Anomalies, unexpected successes, and unexpected failures
    are all valid discovery triggers.
    """

    async def scan_for_contradictions(
        self,
        domain: str = "",
        scope: str = "",
    ) -> list[ContradictionReport]:
        """Systematically scan for contradictions across evidence."""
        ...

    async def scan_for_anomalies(
        self,
        domain: str = "",
    ) -> list[CuriositySignal]:
        """Scan for observations that don't fit existing models."""
        ...

    async def analyze_contradiction(
        self,
        contradiction_id: str,
    ) -> dict[str, Any]:
        """Deep analysis of a contradiction — identify hidden variables."""
        ...

    async def detect_unexpected_outcomes(
        self,
        program_id: str = "",
    ) -> list[CuriositySignal]:
        """Detect unexpected successes and failures in experiments."""
        ...


@runtime_checkable
class IEvidenceEvaluator(Protocol):
    """Scores evidence quality, weight, bias, and trust.

    Every piece of evidence must be evaluated before it touches beliefs.
    The evaluation produces an ``EvidenceAssessment`` whose dimensions
    map directly to ``BeliefConfidence`` dimensions.
    """

    async def evaluate(
        self,
        evidence_id: str,
    ) -> EvidenceAssessment:
        """Full evidence evaluation — quality, bias, trust."""
        ...

    async def compute_weight(
        self,
        evidence_id: str,
    ) -> float:
        """Compute the evidence weight for belief revision."""
        ...

    async def detect_bias(
        self,
        evidence_id: str,
    ) -> list[str]:
        """Detect potential biases in the evidence."""
        ...


@runtime_checkable
class ICuriosityEngine(Protocol):
    """Self-directed investigation prioritization.

    Decides *what* to investigate when there is no user prompt.
    Optimizes for value, not just uncertainty::

        Priority = (Info Gain × Impact × Novelty × Strategic Relevance)
                   ──────────────────────────────────────────────────────
                   (CPU Cost + Time Cost + Risk + Attention Cost)

    Sometimes the optimal action is: don't investigate.
    """

    async def prioritize_investigations(
        self,
        budget: InvestigationBudget | None = None,
    ) -> list[CuriositySignal]:
        """Rank all known unknowns and signals by investigation priority."""
        ...

    async def estimate_value_of_knowing(
        self,
        unknown_id: str,
    ) -> float:
        """Estimate the value of resolving a specific unknown."""
        ...

    async def generate_spontaneous_unknowns(self) -> list[str]:
        """Scan for uncertainty hotspots and generate new UnknownNodes.

        Returns:
            List of newly created UnknownNode IDs.
        """
        ...


@runtime_checkable
class IExplanationEngine(Protocol):
    """Answers 'Why do you believe this?' via graph traversal.

    Not generated text — structured provenance chains through HCIR nodes.
    One of HBLLM's strongest potential features: every belief is
    traceable back to observations through evidence and experiments.
    """

    async def explain_belief(
        self,
        belief_id: str,
    ) -> ExplanationChain:
        """Trace a belief back to its supporting and counter evidence."""
        ...

    async def explain_confidence(
        self,
        belief_id: str,
    ) -> dict[str, float]:
        """Return the confidence decomposition for a belief."""
        ...

    async def trace_to_observations(
        self,
        belief_id: str,
    ) -> list[str]:
        """Follow the full provenance chain to original observations."""
        ...


@runtime_checkable
class ISourceReputationTracker(Protocol):
    """Tracks the reliability of knowledge sources over time.

    Learns which sources are reliable, which reasoning patterns work,
    and which hypothesis origins historically succeed.
    """

    async def record_outcome(
        self,
        source_id: str,
        claim_id: str,
        confirmed: bool,
    ) -> None:
        """Record whether a claim from a source was confirmed."""
        ...

    async def get_reputation(
        self,
        source_id: str,
    ) -> float:
        """Get the reliability score for a source [0.0, 1.0]."""
        ...

    async def get_top_sources(
        self,
        domain: str = "",
        limit: int = 10,
    ) -> list[tuple[str, float]]:
        """Return the most reliable sources for a domain."""
        ...


# ═══════════════════════════════════════════════════════════════════════════
# Wave 3 — Meta-Cognition Data Types
# ═══════════════════════════════════════════════════════════════════════════


@dataclass
class ConfidenceSnapshot:
    """A point-in-time snapshot of a belief's multi-dimensional confidence.

    Used by EpistemicMemory to track confidence trajectories over time.
    """

    belief_id: str = ""
    derived_confidence: float = 0.0
    evidence_quality: float = 0.0
    evidence_quantity: float = 0.0
    reproducibility: float = 0.0
    prediction_accuracy: float = 0.0
    model_agreement: float = 0.0
    source_trust: float = 0.0
    timestamp: float = field(default_factory=time.time)


@dataclass
class CalibrationReport:
    """Full epistemic calibration assessment.

    Answers: "How good am I at knowing things?"

    This is meta-level assessment of the system's overall epistemic
    performance, not per-belief confidence.
    """

    overall_calibration: float = 0.0  # 0=perfect, 1=maximally miscalibrated
    overconfidence_bias: float = 0.0  # >0 = overconfident, <0 = underconfident
    hypothesis_survival_rate: float = 0.0  # % of hypotheses that survived testing
    falsification_rate: float = 0.0  # % of hypotheses actively falsified
    prediction_accuracy: float = 0.0  # Overall prediction accuracy
    total_predictions: int = 0  # Number of predictions evaluated
    total_hypotheses: int = 0  # Number of hypotheses evaluated
    domain_calibration: dict[str, float] = field(default_factory=dict)
    evidence_bias: dict[str, float] = field(default_factory=dict)
    recommendations: list[str] = field(default_factory=list)
    timestamp: float = field(default_factory=time.time)


@dataclass
class CounterfactualResult:
    """Result of a 'what if' epistemic analysis.

    Describes how beliefs would change under hypothetical modifications
    to the evidence graph.  Never modifies the real graph.
    """

    scenario: str = ""  # Human-readable description
    mutation_type: str = ""  # "remove_evidence", "falsify_hypothesis", etc.
    mutation_target_id: str = ""  # ID of the modified node
    affected_beliefs: list[str] = field(default_factory=list)
    confidence_deltas: dict[str, float] = field(default_factory=dict)
    cascading_effects: list[str] = field(default_factory=list)
    structural_impact: float = 0.0  # 0-1: how much the belief graph changed


# ═══════════════════════════════════════════════════════════════════════════
# Wave 3 — Meta-Cognition Protocols
# ═══════════════════════════════════════════════════════════════════════════


@runtime_checkable
class IEpistemicMemory(Protocol):
    """Universal epistemic memory — the history of reasoning.

    Stores things the graph and workspace don't track:
    past hypotheses (abandoned, falsified), failed predictions,
    evidence retractions, confidence trajectories, calibration data.

    Any epistemic consumer can use this memory.
    """

    async def record_hypothesis_outcome(
        self,
        hypothesis_id: str,
        outcome: str,
        reason: str,
    ) -> None:
        """Record a hypothesis's final outcome (falsified, promoted, abandoned)."""
        ...

    async def record_prediction_result(
        self,
        outcome: PredictionOutcome,
    ) -> None:
        """Record a prediction outcome for calibration analysis."""
        ...

    async def record_evidence_retraction(
        self,
        evidence_id: str,
        reason: str,
    ) -> None:
        """Record that evidence was retracted or superseded."""
        ...

    async def snapshot_belief_confidence(
        self,
        belief_id: str,
        snapshot: ConfidenceSnapshot,
    ) -> None:
        """Record a point-in-time confidence snapshot."""
        ...

    async def get_prediction_accuracy(
        self,
        hypothesis_id: str = "",
    ) -> float:
        """Compute prediction accuracy over stored history."""
        ...

    async def get_confidence_trajectory(
        self,
        belief_id: str,
    ) -> list[ConfidenceSnapshot]:
        """Get the confidence trajectory for a belief over time."""
        ...

    async def get_calibration_data(
        self,
        domain: str = "",
    ) -> list[dict[str, Any]]:
        """Get raw calibration data (predicted confidence vs actual outcome)."""
        ...


@runtime_checkable
class IEpistemicCalibrator(Protocol):
    """Meta-epistemic self-calibration.

    Answers: "How good am I at knowing things?"

    Different from self_model/confidence_estimator which estimates
    per-task confidence.  This is system-wide epistemic calibration
    across all domains and reasoning history.
    """

    async def calibrate(self) -> CalibrationReport:
        """Run full calibration analysis."""
        ...

    async def detect_epistemic_biases(self) -> list[str]:
        """Identify systematic biases in the system's reasoning."""
        ...

    async def recommend_strategy_adjustment(self) -> str | None:
        """Recommend a ResearchStrategyType change based on calibration."""
        ...


@runtime_checkable
class ICounterfactualReasoner(Protocol):
    """'What if...' reasoning via cognitive graph modification.

    Creates temporary graph forks to evaluate how beliefs would
    change under hypothetical modifications.  Never modifies
    the real graph.

    Complementary to simulation/models.py CounterfactualScenario:
    that operates at the planning level (tasks → world states);
    this operates at the epistemic level (evidence → beliefs).
    """

    async def what_if_hypothesis_wrong(
        self,
        hypothesis_id: str,
    ) -> CounterfactualResult:
        """What would change if this hypothesis were falsified?"""
        ...

    async def what_if_evidence_removed(
        self,
        evidence_id: str,
    ) -> CounterfactualResult:
        """What would change if this evidence were retracted?"""
        ...

    async def what_if_evidence_quality(
        self,
        evidence_id: str,
        new_quality: float,
    ) -> CounterfactualResult:
        """What would change if this evidence quality were different?"""
        ...

    async def sensitivity_analysis(
        self,
        belief_id: str,
    ) -> dict[str, float]:
        """Find which evidence has the highest impact on this belief.

        Returns:
            Dict of evidence_id → impact score (how much removing
            that evidence would change the belief's confidence).
        """
        ...

