"""Predictive Model Registry — HCIR-native model tracking for A14.

Each predictive model is a PredictiveModelNode in the HCIR graph,
enabling A12 operators to reason about model reliability.

The registry maintains prediction lineage:

    PredictiveModel
          │
          ├── PredictionNode (generated by this model)
          │      ↓
          │   Observation
          │      ↓
          │   PredictionError
          │
          └── AdaptationEvent (ADAPTED_BY edge)
                 ↓
           updated parameters

The system can explain WHY its model has the parameters it has.
"""

from __future__ import annotations

import logging
import time
from typing import Any

from hbllm.hcir.graph import (
    CognitiveGraph,
    HCIRNodeType,
    PredictiveModelNode,
)

logger = logging.getLogger(__name__)


class PredictiveModelRegistry:
    """HCIR-native registry of predictive models with accuracy tracking.

    Every registered model is a PredictiveModelNode in the graph.
    A12 operators can query model reliability; A14 can adapt parameters.

    Usage::

        registry = PredictiveModelRegistry(graph)
        model_id = registry.register(
            model_type="markov",
            domain="physics",
            parameters={"transitions": {...}},
        )

        model = registry.get_model(model_id)
        best = registry.best_model_for("physics")
        trend = registry.accuracy_trend(model_id)
    """

    def __init__(self, graph: CognitiveGraph) -> None:
        self._graph = graph
        # In-memory accuracy history: model_id → list of (timestamp, accuracy)
        self._accuracy_history: dict[str, list[tuple[float, float]]] = {}

    def register(
        self,
        model_type: str,
        domain: str,
        parameters: dict[str, Any] | None = None,
        initial_accuracy: float = 0.5,
        timestamp: float | None = None,
    ) -> str:
        """Register a new predictive model in HCIR.

        Returns:
            The ID of the created PredictiveModelNode.
        """
        now = timestamp if timestamp is not None else time.time()

        model = PredictiveModelNode(
            model_type=model_type,
            domain=domain,
            parameters=parameters or {},
            accuracy=initial_accuracy,
            calibration=0.5,
            created_at=now,
            tags=["predictive_model", model_type, domain],
        )
        self._graph.add_node(model)

        self._accuracy_history[model.id] = [(now, initial_accuracy)]

        logger.debug(
            "PredictiveModelRegistry: registered model %s (%s/%s)",
            model.id,
            model_type,
            domain,
        )

        return model.id

    def get_model(self, model_id: str) -> PredictiveModelNode | None:
        """Retrieve a model by ID."""
        node = self._graph.get_node(model_id)
        if isinstance(node, PredictiveModelNode):
            return node
        return None

    def record_prediction_outcome(
        self,
        model_id: str,
        correct: bool,
        timestamp: float | None = None,
    ) -> None:
        """Record whether a prediction was correct.

        Updates the running accuracy of the model.
        """
        now = timestamp if timestamp is not None else time.time()
        model = self.get_model(model_id)
        if model is None:
            return

        model.prediction_count += 1
        # Exponential moving average for accuracy
        alpha = 0.1
        outcome = 1.0 if correct else 0.0
        model.accuracy = model.accuracy * (1 - alpha) + outcome * alpha

        self._graph.upsert_node(model)

        if model_id not in self._accuracy_history:
            self._accuracy_history[model_id] = []
        self._accuracy_history[model_id].append((now, model.accuracy))

    def best_model_for(self, domain: str) -> PredictiveModelNode | None:
        """Return the highest-accuracy model for a domain."""
        best: PredictiveModelNode | None = None
        best_accuracy = -1.0

        for node in self._graph.nodes_by_type(HCIRNodeType.PREDICTIVE_MODEL):
            if isinstance(node, PredictiveModelNode) and node.domain == domain:
                if node.accuracy > best_accuracy:
                    best = node
                    best_accuracy = node.accuracy

        return best

    def accuracy_trend(
        self,
        model_id: str,
        last_n: int = 10,
    ) -> str:
        """Determine whether a model's accuracy is improving, degrading, or stable.

        Returns:
            "improving", "degrading", or "stable".
        """
        history = self._accuracy_history.get(model_id, [])
        if len(history) < 2:
            return "stable"

        recent = history[-last_n:]
        if len(recent) < 2:
            return "stable"

        first_half = recent[: len(recent) // 2]
        second_half = recent[len(recent) // 2 :]

        avg_first = sum(a for _, a in first_half) / len(first_half)
        avg_second = sum(a for _, a in second_half) / len(second_half)

        delta = avg_second - avg_first
        if delta > 0.02:
            return "improving"
        elif delta < -0.02:
            return "degrading"
        return "stable"

    def models_needing_adaptation(
        self,
        accuracy_threshold: float = 0.4,
    ) -> list[PredictiveModelNode]:
        """Return models with accuracy below threshold."""
        results: list[PredictiveModelNode] = []
        for node in self._graph.nodes_by_type(HCIRNodeType.PREDICTIVE_MODEL):
            if isinstance(node, PredictiveModelNode):
                if node.accuracy < accuracy_threshold:
                    results.append(node)
        return results

    def models_by_domain(self, domain: str) -> list[PredictiveModelNode]:
        """Return all models for a domain."""
        results: list[PredictiveModelNode] = []
        for node in self._graph.nodes_by_type(HCIRNodeType.PREDICTIVE_MODEL):
            if isinstance(node, PredictiveModelNode) and node.domain == domain:
                results.append(node)
        return results

    @property
    def total_models(self) -> int:
        return len(list(self._graph.nodes_by_type(HCIRNodeType.PREDICTIVE_MODEL)))
