"""
Abduction Operator — inference to best explanation over HCIR.

Given a surprising observation, generates candidate explanations
ranked by parsimony (fewer assumptions), coverage (explains more
observations), and consistency with existing beliefs.

Example::

    Surprising observation: "entity_17 stopped moving"
    Candidate explanations:
        1. "entity_17 collided with a wall"     (parsimony=1, coverage=0.8)
        2. "entity_17 ran out of energy"         (parsimony=1, coverage=0.6)
        3. "entity_17 was grasped by entity_22"  (parsimony=2, coverage=0.9)

This is the complement of deduction: where deduction goes
    premises → conclusion, abduction goes observation → best premise.

Independence Level: L1 (no LLM execution)
"""

from __future__ import annotations

import logging
import time
from dataclasses import dataclass, field
from typing import Any

from hbllm.brain.reasoning.operators.base import (
    CognitiveContext,
    CognitiveResult,
    ProblemType,
    ProvenanceChain,
    ReasoningProblem,
    ResourceCost,
    ResultStatus,
)
from hbllm.hcir.graph import (
    BeliefNode,
    ContradictionNode,
    HCIREdgeType,
    HCIRNodeType,
    HypothesisNode,
    PredictionErrorNode,
)
from hbllm.hcir.transactions import TransactionOp, TransactionOperation
from hbllm.hcir.types import Provenance

logger = logging.getLogger(__name__)


@dataclass
class CandidateExplanation:
    """A candidate explanation generated by abduction."""

    claim: str
    parsimony: int  # Number of new assumptions required (lower = better)
    coverage: float  # Fraction of observations explained [0, 1]
    consistency: float  # Consistency with existing beliefs [0, 1]
    evidence_for: list[str] = field(default_factory=list)  # Supporting node IDs
    evidence_against: list[str] = field(default_factory=list)  # Contradicting node IDs
    assumptions: list[str] = field(default_factory=list)

    @property
    def composite_score(self) -> float:
        """Rank candidates: coverage × consistency / (1 + parsimony)."""
        return self.coverage * self.consistency / (1 + self.parsimony)


class AbductionOperator:
    """Inference to best explanation over HCIR state.

    Strategy:
        1. Identify the explanandum — what needs explaining.
        2. Search HCIR for causal/supports/predicts edges pointing
           toward similar observations.
        3. Generate candidate explanations from causal predecessors.
        4. Rank by parsimony, coverage, consistency.
        5. Propose top-N as HypothesisNodes.
    """

    @property
    def operator_id(self) -> str:
        return "abduction"

    @property
    def operator_name(self) -> str:
        return "Abductive Inference Engine"

    @property
    def prerequisites(self) -> tuple[str, ...]:
        return ()

    def can_handle(
        self,
        problem: ReasoningProblem,
        context: CognitiveContext,
    ) -> float:
        type_scores: dict[ProblemType, float] = {
            ProblemType.EXPLANATION: 0.9,
            ProblemType.DIAGNOSIS: 0.85,
            ProblemType.CONTRADICTION: 0.7,
            ProblemType.CAUSAL: 0.6,
            ProblemType.PREDICTION: 0.3,
        }
        base = type_scores.get(problem.problem_type, 0.1)

        view = context.graph_view
        # Abduction needs something to explain — observations, prediction errors, contradictions
        n_explainable = (
            len(view.nodes_by_type(HCIRNodeType.OBSERVATION))
            + len(view.nodes_by_type(HCIRNodeType.PREDICTION_ERROR))
            + len(view.nodes_by_type(HCIRNodeType.CONTRADICTION))
        )
        if n_explainable == 0 and not problem.focus_node_ids:
            return 0.0

        return min(1.0, base + min(0.2, n_explainable * 0.03))

    def estimated_cost(
        self,
        problem: ReasoningProblem,
        context: CognitiveContext,
    ) -> ResourceCost:
        n = context.graph_view.node_count
        return ResourceCost(
            wall_clock_ms=max(2.0, n * 0.3),
            nodes_read=n,
            edges_read=context.graph_view.edge_count,
        )

    def execute(
        self,
        problem: ReasoningProblem,
        context: CognitiveContext,
    ) -> CognitiveResult:
        """Generate ranked explanations for surprising observations."""
        start = time.time()
        view = context.graph_view
        max_hypotheses = min(5, context.budget.max_operators + 2)

        # ── Step 1: Identify the explanandum ─────────────────────────
        explananda = self._identify_explananda(view, problem)

        if not explananda:
            return CognitiveResult(
                status=ResultStatus.NO_RESULT,
                operator_id=self.operator_id,
                metadata={"reason": "Nothing to explain in the view"},
                resource_cost=ResourceCost(
                    wall_clock_ms=(time.time() - start) * 1000,
                    nodes_read=view.node_count,
                ),
            )

        # ── Step 2: Generate candidate explanations ──────────────────
        candidates = self._generate_candidates(view, explananda)

        if not candidates:
            return CognitiveResult(
                status=ResultStatus.NO_RESULT,
                operator_id=self.operator_id,
                conclusions={"explananda_count": len(explananda)},
                metadata={"reason": "No candidate explanations found"},
                resource_cost=ResourceCost(
                    wall_clock_ms=(time.time() - start) * 1000,
                    nodes_read=view.node_count,
                ),
            )

        # ── Step 3: Rank and select top-N ────────────────────────────
        candidates.sort(key=lambda c: c.composite_score, reverse=True)
        top = candidates[:max_hypotheses]

        # ── Step 4: Build result ─────────────────────────────────────
        proposed_ops: list[TransactionOperation] = []
        provenance_chains: list[ProvenanceChain] = []
        evidence_refs: list[str] = []

        for rank, candidate in enumerate(top):
            hyp = HypothesisNode(
                claim=candidate.claim,
                origin="abduction",
                provenance=Provenance(
                    created_by=self.operator_id,
                    source_type="inferred",
                    reason=(
                        f"Abductive hypothesis #{rank + 1}: "
                        f"parsimony={candidate.parsimony}, "
                        f"coverage={candidate.coverage:.2f}, "
                        f"consistency={candidate.consistency:.2f}"
                    ),
                ),
            )
            hyp.uncertainty.confidence = candidate.composite_score
            hyp.plausibility = min(1.0, candidate.composite_score)
            hyp.novelty = 0.5

            proposed_ops.append(
                TransactionOperation(
                    op=TransactionOp.ADD_NODE,
                    node_data=hyp.model_dump(),
                )
            )

            provenance_chains.append(
                ProvenanceChain(
                    conclusion=candidate.claim,
                    evidence_node_ids=candidate.evidence_for,
                    operator_id=self.operator_id,
                    reasoning_steps=[
                        f"Rank #{rank + 1} of {len(candidates)} candidates",
                        f"Parsimony: {candidate.parsimony}",
                        f"Coverage: {candidate.coverage:.3f}",
                        f"Consistency: {candidate.consistency:.3f}",
                        f"Composite: {candidate.composite_score:.3f}",
                    ],
                    assumptions=candidate.assumptions,
                    confidence=candidate.composite_score,
                )
            )
            evidence_refs.extend(candidate.evidence_for)

        evidence_refs = list(dict.fromkeys(evidence_refs))
        elapsed_ms = (time.time() - start) * 1000

        return CognitiveResult(
            status=ResultStatus.SUCCESS,
            conclusions={
                "hypotheses_count": len(top),
                "hypotheses": [
                    {
                        "claim": c.claim,
                        "score": round(c.composite_score, 4),
                        "parsimony": c.parsimony,
                    }
                    for c in top
                ],
                "total_candidates": len(candidates),
            },
            confidence=top[0].composite_score if top else 0.0,
            evidence_refs=evidence_refs,
            assumptions=["Best-explanation ranking is heuristic"],
            proposed_transitions=proposed_ops,
            provenance_chains=provenance_chains,
            operator_id=self.operator_id,
            resource_cost=ResourceCost(
                wall_clock_ms=elapsed_ms,
                nodes_read=view.node_count,
                edges_read=view.edge_count,
            ),
        )

    # ── Internal Methods ─────────────────────────────────────────────

    @staticmethod
    def _identify_explananda(
        view: Any,
        problem: ReasoningProblem,
    ) -> list[dict[str, Any]]:
        """Find things that need explaining."""
        explananda: list[dict[str, Any]] = []

        # Focus nodes from the problem
        for nid in problem.focus_node_ids:
            node = view.get_node(nid)
            if node is not None:
                explananda.append(
                    {
                        "node_id": nid,
                        "type": str(node.node_type),
                        "description": getattr(node, "claim", "")
                        or getattr(node, "description", "")
                        or nid,
                    }
                )

        # Prediction errors — something unexpected happened
        for node in view.nodes_by_type(HCIRNodeType.PREDICTION_ERROR):
            if isinstance(node, PredictionErrorNode) and node.error_magnitude > 0.1:
                explananda.append(
                    {
                        "node_id": node.id,
                        "type": "prediction_error",
                        "description": (
                            f"Expected {node.predicted_value}, observed {node.observed_value}"
                        ),
                    }
                )

        # Contradictions — beliefs in conflict
        for node in view.nodes_by_type(HCIRNodeType.CONTRADICTION):
            if isinstance(node, ContradictionNode):
                explananda.append(
                    {
                        "node_id": node.id,
                        "type": "contradiction",
                        "description": getattr(node, "description", node.id),
                    }
                )

        return explananda

    @staticmethod
    def _generate_candidates(
        view: Any,
        explananda: list[dict[str, Any]],
    ) -> list[CandidateExplanation]:
        """Generate candidate explanations from HCIR structure.

        Strategy:
            - Follow CAUSES, SUPPORTS, PREDICTS edges backward from
              the explanandum to find potential causes.
            - Each causal predecessor becomes a candidate explanation.
            - Score by consistency with other beliefs.
        """
        candidates: list[CandidateExplanation] = []
        seen_claims: set[str] = set()

        # Collect all beliefs for consistency checking
        all_beliefs: dict[str, float] = {}
        for node in view.nodes_by_type(HCIRNodeType.BELIEF):
            if isinstance(node, BeliefNode):
                all_beliefs[node.claim.strip().lower()] = node.uncertainty.confidence

        causal_edge_types = {
            HCIREdgeType.CAUSES,
            HCIREdgeType.SUPPORTS,
            HCIREdgeType.PREDICTS,
        }

        for explanandum in explananda:
            nid = explanandum["node_id"]

            # Look for edges pointing TO this node (causes of the observation)
            incoming_edges = view.edges_to(nid)
            for edge in incoming_edges:
                if edge.edge_type not in causal_edge_types:
                    continue

                for source_id in edge.sources:
                    source_node = view.get_node(source_id)
                    if source_node is None:
                        continue

                    claim = (
                        getattr(source_node, "claim", "")
                        or getattr(source_node, "description", "")
                        or f"node {source_id} caused {explanandum['description']}"
                    )
                    claim_lower = claim.strip().lower()

                    if claim_lower in seen_claims:
                        continue
                    seen_claims.add(claim_lower)

                    # Consistency with existing beliefs
                    consistency = 0.5  # Neutral default
                    evidence_for: list[str] = [source_id]
                    evidence_against: list[str] = []

                    for belief_claim, belief_conf in all_beliefs.items():
                        if claim_lower in belief_claim or belief_claim in claim_lower:
                            consistency = max(consistency, belief_conf)
                            evidence_for.append(source_id)

                    candidates.append(
                        CandidateExplanation(
                            claim=claim,
                            parsimony=1,  # Single-cause explanation
                            coverage=edge.weight if edge.weight > 0 else 0.5,
                            consistency=consistency,
                            evidence_for=evidence_for,
                            evidence_against=evidence_against,
                            assumptions=[
                                f"Assumes {source_id} causally explains "
                                f"{explanandum['description']}"
                            ],
                        )
                    )

        # If no structural candidates found, generate from
        # high-confidence beliefs that could explain the observation
        if not candidates:
            for explanandum in explananda:
                desc = explanandum["description"].lower()
                for belief_claim, belief_conf in all_beliefs.items():
                    if belief_conf >= 0.6:
                        # Check for any semantic overlap (very simple)
                        words_desc = set(desc.split())
                        words_belief = set(belief_claim.split())
                        overlap = words_desc & words_belief - {
                            "the",
                            "a",
                            "is",
                            "are",
                            "was",
                            "has",
                        }
                        if len(overlap) >= 2:
                            candidates.append(
                                CandidateExplanation(
                                    claim=f"possibly explained by: {belief_claim}",
                                    parsimony=2,
                                    coverage=len(overlap) / max(1, len(words_desc)),
                                    consistency=belief_conf,
                                    evidence_for=[],
                                    assumptions=["Weak semantic overlap as proxy for explanation"],
                                )
                            )

        return candidates
