"""
DPO Dataset Export CLI.

Consolidates preference data from multiple HBLLM sources into a single
HuggingFace-compatible DPO training dataset.  Supports three data sources:

1. **DPO Queue** — live preference pairs queued by the LearnerNode
   (``workspace/reflection/dpo_queue.json``).
2. **Reflection Logs** — JSONL files generated by MetaReasoningNode after
   systemic weakness detection (``workspace/reflection/reflection_*.jsonl``).
3. **Interaction DB** — preference pairs mined from user regeneration events
   via the InteractionMiner.

Output format follows the standard ``{"prompt", "chosen", "rejected"}`` schema
used by TRL's ``DPOTrainer``.

Usage::

    python -m hbllm.cli.export_dpo --output dpo_dataset.jsonl
    python -m hbllm.cli.export_dpo --source queue --output dpo_queue.jsonl
    python -m hbllm.cli.export_dpo --source mined --min-reward 0.5 --output mined.jsonl
"""

from __future__ import annotations

import argparse
import json
import logging
import sys
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)


# ── Data Source Readers ──────────────────────────────────────────────────────

def read_dpo_queue(queue_path: str | Path) -> list[dict[str, str]]:
    """
    Read preference pairs from the LearnerNode's DPO queue.

    Expected format: list of ``[prompt, chosen, rejected]`` triples.
    """
    queue_path = Path(queue_path)
    if not queue_path.exists():
        logger.warning("DPO queue not found at %s", queue_path)
        return []

    try:
        with open(queue_path) as f:
            raw = json.load(f)
    except (json.JSONDecodeError, OSError) as e:
        logger.error("Failed to read DPO queue: %s", e)
        return []

    pairs: list[dict[str, str]] = []
    for item in raw:
        if isinstance(item, (list, tuple)) and len(item) >= 3:
            pairs.append({
                "prompt": str(item[0]),
                "chosen": str(item[1]),
                "rejected": str(item[2]),
            })
        elif isinstance(item, dict):
            prompt = item.get("prompt") or item.get("instruction", "")
            chosen = item.get("chosen") or item.get("response", "")
            rejected = item.get("rejected", "")
            if prompt and chosen and rejected:
                pairs.append({"prompt": prompt, "chosen": chosen, "rejected": rejected})

    logger.info("Read %d preference pairs from DPO queue", len(pairs))
    return pairs


def read_reflection_logs(reflection_dir: str | Path) -> list[dict[str, str]]:
    """
    Read rejected interaction samples from MetaReasoningNode reflection logs.

    Each ``.jsonl`` file contains records with ``instruction`` and ``response``
    fields that represent *rejected* outputs.  A synthetic chosen response is
    generated as a placeholder prompt for the downstream DPO trainer.
    """
    reflection_dir = Path(reflection_dir)
    if not reflection_dir.exists():
        logger.warning("Reflection dir not found at %s", reflection_dir)
        return []

    pairs: list[dict[str, str]] = []
    for jsonl_file in sorted(reflection_dir.glob("reflection_*.jsonl")):
        try:
            with open(jsonl_file) as f:
                for line in f:
                    line = line.strip()
                    if not line:
                        continue
                    record = json.loads(line)
                    instruction = record.get("instruction", "")
                    rejected = record.get("response", "")
                    domain = record.get("domain", "unknown")

                    if instruction and rejected:
                        pairs.append({
                            "prompt": instruction,
                            "chosen": "",  # to be filled by trainer with model output
                            "rejected": rejected,
                            "domain": domain,
                            "source": "reflection",
                        })
        except (json.JSONDecodeError, OSError) as e:
            logger.warning("Skipping corrupt reflection file %s: %s", jsonl_file, e)

    logger.info("Read %d rejected samples from %s", len(pairs), reflection_dir)
    return pairs


def read_mined_pairs(
    data_dir: str | Path = "data",
    min_reward: float = 0.3,
    limit: int = 5000,
) -> list[dict[str, str]]:
    """
    Mine preference pairs from the InteractionMiner database.

    Uses regeneration events where the original response is rejected and
    the follow-up response is chosen.
    """
    try:
        from hbllm.data.interaction_miner import InteractionMiner
    except ImportError:
        logger.warning("InteractionMiner not available")
        return []

    miner = InteractionMiner(data_dir=str(data_dir))
    raw_pairs = miner.mine_preference_pairs(limit=limit)

    pairs: list[dict[str, str]] = []
    for p in raw_pairs:
        pairs.append({
            "prompt": p.get("query", ""),
            "chosen": p.get("chosen", ""),
            "rejected": p.get("rejected", ""),
            "source": "mined",
        })

    logger.info("Mined %d preference pairs (min_reward=%.2f)", len(pairs), min_reward)
    return pairs


# ── Export Logic ─────────────────────────────────────────────────────────────

def collect_all_pairs(
    workspace_dir: str | Path = "workspace",
    data_dir: str | Path = "data",
    sources: list[str] | None = None,
    min_reward: float = 0.3,
) -> list[dict[str, str]]:
    """
    Collect DPO pairs from all configured sources.

    Args:
        workspace_dir: Base workspace directory.
        data_dir: InteractionMiner database directory.
        sources: List of sources to include (``queue``, ``reflection``, ``mined``).
                 Defaults to all sources.
        min_reward: Minimum reward threshold for mined pairs.

    Returns:
        Deduplicated list of preference pair dicts.
    """
    workspace_dir = Path(workspace_dir)
    sources = sources or ["queue", "reflection", "mined"]

    all_pairs: list[dict[str, str]] = []

    if "queue" in sources:
        queue_path = workspace_dir / "reflection" / "dpo_queue.json"
        all_pairs.extend(read_dpo_queue(queue_path))

    if "reflection" in sources:
        reflection_dir = workspace_dir / "reflection"
        all_pairs.extend(read_reflection_logs(reflection_dir))

    if "mined" in sources:
        all_pairs.extend(read_mined_pairs(data_dir, min_reward=min_reward))

    # Deduplicate by prompt+rejected hash
    seen: set[str] = set()
    unique: list[dict[str, str]] = []
    for pair in all_pairs:
        key = f"{pair.get('prompt', '')}||{pair.get('rejected', '')}"
        if key not in seen:
            seen.add(key)
            unique.append(pair)

    logger.info(
        "Collected %d unique DPO pairs (%d before dedup) from sources: %s",
        len(unique), len(all_pairs), sources,
    )
    return unique


def export_jsonl(pairs: list[dict[str, str]], output_path: str | Path) -> int:
    """
    Write DPO pairs to a JSONL file in TRL-compatible format.

    Each line: ``{"prompt": "...", "chosen": "...", "rejected": "..."}``

    Returns:
        Number of records written.
    """
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    count = 0
    with open(output_path, "w") as f:
        for pair in pairs:
            record = {
                "prompt": pair.get("prompt", ""),
                "chosen": pair.get("chosen", ""),
                "rejected": pair.get("rejected", ""),
            }
            # Only write if we have at minimum a prompt and one response
            if record["prompt"] and (record["chosen"] or record["rejected"]):
                f.write(json.dumps(record, ensure_ascii=False) + "\n")
                count += 1

    logger.info("Exported %d DPO pairs to %s", count, output_path)
    return count


def build_stats(pairs: list[dict[str, str]]) -> dict[str, Any]:
    """Compute summary statistics for a DPO dataset."""
    sources: dict[str, int] = {}
    domains: dict[str, int] = {}
    complete = 0

    for p in pairs:
        src = p.get("source", "queue")
        sources[src] = sources.get(src, 0) + 1
        dom = p.get("domain", "general")
        domains[dom] = domains.get(dom, 0) + 1
        if p.get("chosen") and p.get("rejected"):
            complete += 1

    return {
        "total_pairs": len(pairs),
        "complete_pairs": complete,
        "incomplete_pairs": len(pairs) - complete,
        "sources": sources,
        "domains": domains,
    }


# ── CLI Entry Point ─────────────────────────────────────────────────────────

def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="export_dpo",
        description="Export DPO preference datasets from HBLLM reflection and interaction data.",
    )
    parser.add_argument(
        "--output", "-o",
        default="dpo_dataset.jsonl",
        help="Output file path (default: dpo_dataset.jsonl)",
    )
    parser.add_argument(
        "--workspace", "-w",
        default="workspace",
        help="Workspace directory (default: workspace)",
    )
    parser.add_argument(
        "--data-dir",
        default="data",
        help="InteractionMiner data directory (default: data)",
    )
    parser.add_argument(
        "--source", "-s",
        nargs="+",
        choices=["queue", "reflection", "mined"],
        default=None,
        help="Data sources to include (default: all)",
    )
    parser.add_argument(
        "--min-reward",
        type=float,
        default=0.3,
        help="Minimum reward threshold for mined pairs (default: 0.3)",
    )
    parser.add_argument(
        "--stats",
        action="store_true",
        help="Print dataset statistics to stdout",
    )
    parser.add_argument(
        "--verbose", "-v",
        action="store_true",
        help="Enable verbose logging",
    )

    args = parser.parse_args(argv)

    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO,
        format="%(levelname)s  %(name)s  %(message)s",
    )

    pairs = collect_all_pairs(
        workspace_dir=args.workspace,
        data_dir=args.data_dir,
        sources=args.source,
        min_reward=args.min_reward,
    )

    if not pairs:
        logger.warning("No DPO pairs found. Nothing to export.")
        return 1

    count = export_jsonl(pairs, args.output)

    if args.stats:
        stats = build_stats(pairs)
        print(json.dumps(stats, indent=2))

    print(f"✓ Exported {count} DPO pairs → {args.output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
