"""
Leaky Integrate-and-Fire (LIF) Neuron Model and Accumulator.

Implements a time-dependent spiking neural model where decay is computed
relative to real elapsed time (dt in seconds) rather than discrete cycles,
making it suitable for asynchronous event-driven pipelines.
"""

from __future__ import annotations

import time
from dataclasses import dataclass


@dataclass
class SpikeEvent:
    """Represents a spike generated by a LIF neuron."""

    fired: bool
    strength: float
    timestamp: float


@dataclass
class LIFConfig:
    """Configuration parameter set for a LIF neuron."""

    threshold: float = 1.0
    decay_half_life: float = 1.0  # seconds; time for potential to decay by 50%
    reset_potential: float = 0.0
    refractory_period: float = 0.0  # seconds; cooldown period after firing


class LIFNeuron:
    """
    Leaky Integrate-and-Fire (LIF) Neuron.

    Accumulates input current over time, decays exponentially, and fires a spike
    once the membrane potential crosses a configured threshold.
    """

    def __init__(self, config: LIFConfig) -> None:
        self.config = config
        self.v = 0.0  # Membrane potential
        self.last_update_time: float | None = None
        self.refractory_time_remaining: float = 0.0

    def step(self, current: float, timestamp: float) -> SpikeEvent:
        """
        Advance the state of the neuron by applying decay and input current.

        Args:
            current: Input value/charge to accumulate on this step.
            timestamp: The epoch timestamp (in seconds) of this step.

        Returns:
            A SpikeEvent detailing if a spike occurred and its strength.
        """
        if self.last_update_time is None:
            self.last_update_time = timestamp

        dt = max(0.0, timestamp - self.last_update_time)
        self.last_update_time = timestamp

        # 1. Update refractory timer
        if self.refractory_time_remaining > 0:
            self.refractory_time_remaining = max(0.0, self.refractory_time_remaining - dt)

        # 2. Decay membrane potential (only if we have non-zero elapsed time)
        if dt > 0.0:
            if self.config.decay_half_life <= 0:
                decay_factor = 0.0
            else:
                # v(t) = v(t0) * 2^(-dt / t_half)
                decay_factor = 2.0 ** (-dt / self.config.decay_half_life)
            self.v *= decay_factor

        # 3. Accumulate current if not in refractory period
        if self.refractory_time_remaining <= 0:
            self.v += current

        # 4. Check if threshold is crossed
        fired = False
        strength = 0.0
        if self.v >= self.config.threshold:
            fired = True
            # Strength is proportional to the overshoot ratio
            strength = self.v / self.config.threshold
            # Reset membrane potential
            self.v = self.config.reset_potential
            # Activate refractory period
            self.refractory_time_remaining = self.config.refractory_period

        return SpikeEvent(fired=fired, strength=strength, timestamp=timestamp)

    def reset_state(self) -> None:
        """Reset the dynamic states of the neuron."""
        self.v = 0.0
        self.last_update_time = None
        self.refractory_time_remaining = 0.0


class SpikingAccumulator:
    """
    A generic accumulator primitive wrapping a LIFNeuron.

    Can be used by any cognitive node to track quantities like attention fatigue,
    error counts, resource load, or threat level over time.
    """

    def __init__(self, config: LIFConfig) -> None:
        self.neuron = LIFNeuron(config)

    def stimulate(self, value: float, timestamp: float | None = None) -> SpikeEvent:
        """
        Inject charge/stimulus into the accumulator.

        Args:
            value: Magnitude of the stimulus.
            timestamp: Optional custom timestamp. Defaults to time.time().
        """
        if timestamp is None:
            timestamp = time.time()
        return self.neuron.step(value, timestamp)

    def get_potential(self, timestamp: float | None = None) -> float:
        """
        Fetch the current decayed membrane potential without adding any stimulus.

        Args:
            timestamp: Optional custom timestamp. Defaults to time.time().
        """
        if timestamp is None:
            timestamp = time.time()
        self.neuron.step(0.0, timestamp)
        return self.neuron.v

    def reset(self) -> None:
        """Reset the accumulator state."""
        self.neuron.reset_state()
