"""
Neuron Model Hierarchy — polymorphic spiking neuron types.

Provides a ``BaseNeuron`` abstract base and multiple neuron model
implementations that produce ``SpikeEvent`` outputs compatible with
the entire SNN pipeline (``NeuronLayer``, ``LayerProjection``,
``SpikingNetwork``).

Available models:

    LIFNeuron          — Leaky Integrate-and-Fire (existing, in lif.py)
    IzhikevichNeuron   — 2-variable model, 20+ biological spiking patterns
    AdExNeuron         — Adaptive Exponential IF (future, for neuromorphic HW)

The ``IzhikevichNeuron`` is the primary upgrade for cognitive processing.
For almost the same computational cost as LIF, it provides:

    - **Bursting**: Evidence accumulation thresholds (reasoning)
    - **Resonance**: Frequency-selective attention
    - **Adaptation**: Cognitive fatigue modeling
    - **Rebound spikes**: Surprise/novelty detection
    - **Inhibitory cells**: Fast-spiking interneurons for WTA competition

Usage::

    from hbllm.brain.snn.neurons import IzhikevichNeuron, IzhikevichConfig

    # Create a regular spiking neuron (cortical excitatory)
    neuron = IzhikevichNeuron(IzhikevichConfig.regular_spiking(), "rs_0")
    spike = neuron.step(current=10.0, timestamp=1.0)

    # Create a fast spiking interneuron (for WTA inhibition)
    inhib = IzhikevichNeuron(IzhikevichConfig.fast_spiking(), "fs_0")

    # Create a bursting neuron (for evidence accumulation)
    burst = IzhikevichNeuron(IzhikevichConfig.intrinsically_bursting(), "ib_0")
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import Any

# ═══════════════════════════════════════════════════════════════════════════
# SpikeEvent — shared output type for all neuron models
# ═══════════════════════════════════════════════════════════════════════════


@dataclass
class SpikeEvent:
    """Represents a spike generated by a spiking neuron.

    This is the universal output type for all ``BaseNeuron.step()`` calls.
    Defined here (in the base types module) to avoid circular imports
    between ``neurons.py`` and model-specific modules like ``lif.py``.
    """

    fired: bool
    strength: float
    timestamp: float


# ═══════════════════════════════════════════════════════════════════════════
# BaseNeuron — abstract base for all neuron models
# ═══════════════════════════════════════════════════════════════════════════


class BaseNeuron(ABC):
    """Abstract base class for all spiking neuron models.

    Every neuron model must implement:

        step(current, timestamp) → SpikeEvent
        reset_state() → None
        get_type() → str

    This ensures any neuron can be used interchangeably in
    ``NeuronLayer``, ``LayerProjection``, and ``SpikingNetwork``.
    """

    neuron_id: str
    v: float  # Membrane potential (subclasses set initial value)

    @abstractmethod
    def step(self, current: float, timestamp: float) -> SpikeEvent:
        """Advance neuron state by one timestep.

        Args:
            current: Input current to the neuron on this step.
            timestamp: Epoch timestamp in seconds.

        Returns:
            A SpikeEvent indicating whether the neuron fired.
        """
        ...

    @abstractmethod
    def reset_state(self) -> None:
        """Reset all dynamic state (membrane potential, recovery, etc.)."""
        ...

    @abstractmethod
    def get_type(self) -> str:
        """Return the neuron model type identifier.

        Used for serialization and polymorphic restoration.
        Example: ``"lif"``, ``"izhikevich"``, ``"adex"``
        """
        ...

    def to_dict(self) -> dict[str, Any]:
        """Serialize dynamic state for persistence.

        Subclasses should override to include model-specific state.
        """
        return {
            "neuron_id": self.neuron_id,
            "type": self.get_type(),
            "v": self.v,
        }


# ═══════════════════════════════════════════════════════════════════════════
# IzhikevichConfig — configuration and preset factory
# ═══════════════════════════════════════════════════════════════════════════


@dataclass
class IzhikevichConfig:
    """Configuration for the Izhikevich neuron model.

    The model is governed by two coupled differential equations::

        dv/dt = 0.04*v² + 5*v + 140 - u + I
        du/dt = a*(b*v - u)

    With the reset rule: if v ≥ v_peak, then v = c, u = u + d.

    Parameters:
        a: Time scale of the recovery variable *u*. Smaller values
           result in slower recovery (0.02 is typical for cortical neurons).
        b: Sensitivity of recovery to subthreshold fluctuations of *v*.
           Values around 0.2 make *u* sensitive to membrane potential.
        c: Post-spike reset value of *v*. Typically -65mV for cortical neurons.
        d: Post-spike jump of recovery variable *u*. Controls spike
           frequency adaptation.
        v_peak: Spike cutoff threshold. When *v* ≥ *v_peak*, the neuron
           fires and resets. Standard value is 30mV.

    Additional parameters:
        is_inhibitory: If True, this neuron's output current is inverted.
        target_firing_rate: Target firing rate for homeostatic plasticity
            (0.0 = disabled).
        adaptation_rate: How fast homeostatic threshold adapts.
    """

    a: float = 0.02
    b: float = 0.2
    c: float = -65.0
    d: float = 8.0
    v_peak: float = 30.0

    # Shared behavioral flags (compatible with LIFConfig interface)
    is_inhibitory: bool = False
    target_firing_rate: float = 0.0
    adaptation_rate: float = 0.01

    # Integration parameters
    dt_substeps: int = 4  # Euler sub-steps per step for stability

    # ── Preset factory methods ──

    @classmethod
    def regular_spiking(cls, **overrides: Any) -> IzhikevichConfig:
        """Cortical excitatory neurons (pyramidal cells).

        Regular, tonic spiking with frequency adaptation.
        Most common cortical neuron type.
        """
        return cls(a=0.02, b=0.2, c=-65.0, d=8.0, **overrides)

    @classmethod
    def fast_spiking(cls, **overrides: Any) -> IzhikevichConfig:
        """Cortical inhibitory interneurons (basket cells).

        Fast, non-adapting spikes. Ideal for WTA lateral inhibition.
        """
        return cls(a=0.1, b=0.2, c=-65.0, d=2.0, is_inhibitory=True, **overrides)

    @classmethod
    def intrinsically_bursting(cls, **overrides: Any) -> IzhikevichConfig:
        """Thalamic relay neurons / Layer 5 pyramidal cells.

        Initial burst followed by tonic spiking. Excellent for
        evidence accumulation — the burst indicates "confidence
        threshold crossed."
        """
        return cls(a=0.02, b=0.2, c=-55.0, d=4.0, **overrides)

    @classmethod
    def chattering(cls, **overrides: Any) -> IzhikevichConfig:
        """Cortical chattering cells.

        Rhythmic bursting at gamma frequencies. Useful for
        binding and synchronization.
        """
        return cls(a=0.02, b=0.2, c=-50.0, d=2.0, **overrides)

    @classmethod
    def low_threshold_spiking(cls, **overrides: Any) -> IzhikevichConfig:
        """Low-threshold spiking (LTS) interneurons.

        Rebound spikes after inhibition, important for
        novelty detection and rebound excitation.
        """
        return cls(a=0.02, b=0.25, c=-65.0, d=2.0, **overrides)

    @classmethod
    def resonator(cls, **overrides: Any) -> IzhikevichConfig:
        """Resonator neurons.

        Respond selectively to oscillatory input at preferred frequency.
        Useful for frequency-selective attention and oscillation detection.
        """
        return cls(a=0.1, b=0.26, c=-60.0, d=-1.0, **overrides)

    @classmethod
    def thalamo_cortical(cls, **overrides: Any) -> IzhikevichConfig:
        """Thalamo-cortical relay neuron.

        Depolarized mode: tonic spiking.
        Hyperpolarized mode: rebound bursting.
        Important for sleep-wake transitions.
        """
        return cls(a=0.02, b=0.25, c=-65.0, d=0.05, **overrides)


# ═══════════════════════════════════════════════════════════════════════════
# IzhikevichNeuron — the primary cognitive neuron model
# ═══════════════════════════════════════════════════════════════════════════


class IzhikevichNeuron(BaseNeuron):
    """Izhikevich spiking neuron model.

    A 2-variable dynamical system that reproduces 20+ biological spiking
    patterns at the computational cost of a leaky integrator.

    Equations (Euler integration with sub-stepping for stability)::

        dv/dt = 0.04*v² + 5*v + 140 - u + I
        du/dt = a*(b*v - u)

        if v ≥ v_peak:
            v ← c
            u ← u + d

    The model uses real-time ``dt`` based on elapsed wall-clock time
    (same pattern as ``LIFNeuron``) for compatibility with the
    asynchronous event-driven pipeline.

    Args:
        config: Izhikevich model parameters. Use presets like
            ``IzhikevichConfig.regular_spiking()`` for common neuron types.
        neuron_id: Unique identifier for this neuron.
    """

    def __init__(
        self,
        config: IzhikevichConfig,
        neuron_id: str = "unknown",
    ) -> None:
        self.config = config
        self.neuron_id = neuron_id

        # Dynamic state
        self.v: float = config.c  # Start at reset potential
        self.u: float = config.b * config.c  # Recovery variable
        self.last_update_time: float | None = None
        self.last_reported_v: float = 0.0

        # Homeostatic plasticity (same interface as LIF)
        self._firing_history: list[bool] = []
        self._homeostatic_window: int = 50
        self._effective_v_peak: float = config.v_peak

    def step(self, current: float, timestamp: float) -> SpikeEvent:
        """Advance the neuron by one timestep.

        Uses sub-stepping for numerical stability of the quadratic ODE.
        The ``dt`` is computed from real elapsed time, making this
        compatible with the asynchronous event-driven pipeline.

        Args:
            current: Input current (arbitrary units, positive = excitatory).
            timestamp: Epoch timestamp in seconds.

        Returns:
            SpikeEvent with firing status and strength.
        """
        cfg = self.config

        if self.last_update_time is None:
            self.last_update_time = timestamp

        dt = max(0.0, timestamp - self.last_update_time)
        self.last_update_time = timestamp

        # Skip if no time elapsed (prevents division by zero)
        if dt <= 0.0:
            return SpikeEvent(fired=False, strength=0.0, timestamp=timestamp)

        # Scale dt to milliseconds for the standard Izhikevich equations
        # (original equations assume dt in ms, our timestamps are in seconds)
        dt_ms = dt * 1000.0

        # Sub-step for numerical stability
        n_sub = max(1, cfg.dt_substeps)
        sub_dt = dt_ms / n_sub

        fired = False
        strength = 0.0

        for _ in range(n_sub):
            if self.v >= self._effective_v_peak:
                # Spike! Reset state
                fired = True
                strength = max(strength, self.v / self._effective_v_peak)
                self.v = cfg.c
                self.u += cfg.d

            # Izhikevich equations (standard form)
            # dv/dt = 0.04*v^2 + 5*v + 140 - u + I
            dv = 0.04 * self.v * self.v + 5.0 * self.v + 140.0 - self.u + current
            # du/dt = a*(b*v - u)
            du = cfg.a * (cfg.b * self.v - self.u)

            self.v += dv * sub_dt
            self.u += du * sub_dt

            # Clamp v to prevent numerical explosion
            if self.v > cfg.v_peak + 50.0:
                self.v = cfg.v_peak + 50.0

        # Final spike check after all sub-steps
        if self.v >= self._effective_v_peak:
            fired = True
            strength = max(strength, self.v / self._effective_v_peak)
            self.v = cfg.c
            self.u += cfg.d

        # Homeostatic plasticity (same logic as LIF)
        if cfg.target_firing_rate > 0.0:
            self._firing_history.append(fired)
            if len(self._firing_history) > self._homeostatic_window:
                self._firing_history = self._firing_history[-self._homeostatic_window :]
            if len(self._firing_history) >= self._homeostatic_window:
                actual_rate = sum(self._firing_history) / len(self._firing_history)
                error = actual_rate - cfg.target_firing_rate
                self._effective_v_peak += error * cfg.adaptation_rate
                self._effective_v_peak = max(
                    cfg.v_peak * 0.5,
                    min(cfg.v_peak * 2.0, self._effective_v_peak),
                )

        # SNN telemetry (same pattern as LIF — delta-filtered)
        if (
            abs(self.v - self.last_reported_v) >= 0.05
            or fired
            or (self.v == 0.0 and self.last_reported_v != 0.0)
        ):
            try:
                from hbllm.network.metrics import MetricsCollector

                MetricsCollector.get_instance().record_snn_potential(self.neuron_id, self.v)
                self.last_reported_v = self.v
            except Exception:
                pass  # Metrics not available

        if fired:
            try:
                from hbllm.network.metrics import MetricsCollector

                MetricsCollector.get_instance().record_snn_spike(self.neuron_id, strength)
            except Exception:
                pass

        return SpikeEvent(fired=fired, strength=strength, timestamp=timestamp)

    def reset_state(self) -> None:
        """Reset all dynamic state to initial conditions."""
        self.v = self.config.c
        self.u = self.config.b * self.config.c
        self.last_update_time = None
        self.last_reported_v = 0.0
        self._firing_history = []
        self._effective_v_peak = self.config.v_peak

    def get_type(self) -> str:
        """Return ``"izhikevich"``."""
        return "izhikevich"

    def to_dict(self) -> dict[str, Any]:
        """Serialize dynamic state for persistence."""
        base = super().to_dict()
        base.update(
            {
                "u": self.u,
                "config": {
                    "a": self.config.a,
                    "b": self.config.b,
                    "c": self.config.c,
                    "d": self.config.d,
                    "v_peak": self.config.v_peak,
                    "is_inhibitory": self.config.is_inhibitory,
                },
            }
        )
        return base

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> IzhikevichNeuron:
        """Restore from persisted state."""
        cfg_data = data.get("config", {})
        config = IzhikevichConfig(
            a=cfg_data.get("a", 0.02),
            b=cfg_data.get("b", 0.2),
            c=cfg_data.get("c", -65.0),
            d=cfg_data.get("d", 8.0),
            v_peak=cfg_data.get("v_peak", 30.0),
            is_inhibitory=cfg_data.get("is_inhibitory", False),
        )
        neuron = cls(config=config, neuron_id=data.get("neuron_id", "unknown"))
        neuron.v = data.get("v", config.c)
        neuron.u = data.get("u", config.b * config.c)
        return neuron


# ═══════════════════════════════════════════════════════════════════════════
# Factory registry — for polymorphic neuron creation from serialized data
# ═══════════════════════════════════════════════════════════════════════════


# Maps type string → (config_class, neuron_class)
_NEURON_REGISTRY: dict[str, type[BaseNeuron]] = {
    "izhikevich": IzhikevichNeuron,
}


def register_neuron_type(type_name: str, neuron_class: type[BaseNeuron]) -> None:
    """Register a custom neuron type for polymorphic deserialization.

    Args:
        type_name: The string identifier (must match ``get_type()``).
        neuron_class: The neuron class with a ``from_dict()`` classmethod.
    """
    _NEURON_REGISTRY[type_name] = neuron_class


def create_neuron_from_dict(data: dict[str, Any]) -> BaseNeuron:
    """Create a neuron from serialized data, dispatching on type.

    Args:
        data: Dict with at least ``"type"`` key.

    Returns:
        An instance of the appropriate neuron subclass.

    Raises:
        ValueError: If the neuron type is not registered.
    """
    neuron_type = data.get("type", "lif")

    if neuron_type == "lif":
        # LIF is special — it lives in lif.py and may not have from_dict
        from hbllm.brain.snn.lif import LIFConfig, LIFNeuron

        neuron = LIFNeuron(
            config=LIFConfig(),
            neuron_id=data.get("neuron_id", "unknown"),
        )
        neuron.v = data.get("v", 0.0)
        return neuron

    if neuron_type not in _NEURON_REGISTRY:
        raise ValueError(
            f"Unknown neuron type: '{neuron_type}'. "
            f"Registered types: {list(_NEURON_REGISTRY.keys())}"
        )

    neuron_cls = _NEURON_REGISTRY[neuron_type]
    if hasattr(neuron_cls, "from_dict"):
        return neuron_cls.from_dict(data)

    raise ValueError(f"Neuron type '{neuron_type}' does not implement from_dict()")
